### ISSUE TITLE
Composant "Video.razor" n'affiche pas la video correctement

### ISSUE THREAD

**Issue by DarOli2131947** [LouisSeranne/DICJ_Stimulus_A23#39]
**Description du bug :**
Que fait-il : Ne fait qu'afficher "www.youtube.com n'autorise pas la connexion"
Quel fichier : Video.razor

**Comment le reproduire :**
Étapes :

Log in avec l'utilisateur "2131947"
1. Cliquez sur 'Test1'
2. Cliquez sur "4"
3. Observer l'erreur

Ce qui était prévu : Avoir une video embed qui contient la lien dans la bd (dbo.video)

**Captures d'écran :**
![image](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89397446/024ac2fb-a3e8-47ed-b1d4-a8862567c9f0)

**Comment by LouisSeranne** [comment]
![image](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89479477/2f53fc09-9ed9-4630-bc10-f5ce8bea8814)

**Comment by LouisSeranne** [comment]
Lien "en savoir plus" : https://support.mozilla.org/fr/kb/page-erreur-reseau-xframe?as=u&utm_source=inproduct
