### ISSUE TITLE
Manque de sécurité de l'interpréteur Python

### ISSUE THREAD

**Issue by YohanTremblay** [LouisSeranne/DICJ_Stimulus_A23#56]
**Description du bug :**
Que fait-il : Fait crash l'application
Quel fichier : Interpréteur Python
Quelle ligne : ???

**Comment le reproduire :**
Étapes : 

Accédez à 'Exercice'
1. Écrire 'while True:'
3. Observer l'erreur
4. Ce qui était prévu : Arrêt avant le crash de l'application
Un bref résumé de ce qui était censé se produire sans le bug.

**Captures d'écran :**
Si possible

**Comment by LouisSeranne** [comment]
Problème réglé à la date du 02/11/2023 dans Docker, mais comme l'intégration Docker n'est pas fini, l'issue n'est pas fermée
