### ISSUE TITLE
Mise au propre du schéma de BD actuelle

### ISSUE THREAD

**Issue by YohanTremblay** [LouisSeranne/DICJ_Stimulus_A23#62]
**Raison de cet ajout :**
Explication de la raison de cette modification : Avoir le schéma de la BD actuelle

**Solution souhaitée :**
Description de la solution souhaitée : Avoir un shéma

**Contexte additionnel :**
Informations contextuelles supplémentaires.

**Comment by Quenat2130288** [comment]
![Diagram_Stimulus](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89397558/614a1bbd-24a9-458b-a447-f28c8ff9cb95)

**Comment by Quenat2130288** [comment]
Schema ci-dessus

**Comment by Quenat2130288** [comment]
![Diagram_Maintenance_Stimulus](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89397558/81f6f53b-9e20-45a0-99f2-81646e03a9ee)

**Comment by Quenat2130288** [comment]
![Diagram_Maintenance_Stimulus](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89397558/a1c7e46d-d89b-471d-a88a-6afc621eb0c7)

**Comment by Quenat2130288** [comment]
![Diagram_Maintenance_Stimulus](https://github.com/LouisSeranne/DICJ_Stimulus_A23/assets/89397558/73d93e75-f910-4869-8611-0f4cb78a03c2)
